// author : vjlang team
import type { Token } from "./model";

function createToken(token: Token): Token {
  return token;
}

export const UNIVERSAL_TOKENS: Token[] = [
  createToken({
    name: "--font-sans",
    value: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Roboto", "Google Sans", "Noto Sans", "Segoe UI", "Ubuntu", "Cantarell", Arial, system-ui, sans-serif',
    category: "font-stacks",
    section: "font-stacks",
    comment: "Body / UI text",
  }),
  createToken({
    name: "--font-display",
    value: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "Google Sans Display", "Roboto", "Segoe UI Display", system-ui, sans-serif',
    category: "font-stacks",
    section: "font-stacks",
    comment: "Display / hero",
  }),
  createToken({
    name: "--font-compact",
    value: '-apple-system, BlinkMacSystemFont, "SF Compact Text", "Roboto Condensed", "Noto Sans", system-ui, sans-serif',
    category: "font-stacks",
    section: "font-stacks",
    comment: "Compact / wearable",
  }),
  createToken({
    name: "--font-mono",
    value: '"SF Mono", "Roboto Mono", "Cascadia Code", "Fira Code", "JetBrains Mono", ui-monospace, "Courier New", monospace',
    category: "font-stacks",
    section: "font-stacks",
    comment: "Monospaced",
  }),
  createToken({
    name: "--font-rounded",
    value: '-apple-system, BlinkMacSystemFont, "SF Pro Rounded", "Google Sans", system-ui, sans-serif',
    category: "font-stacks",
    section: "font-stacks",
    comment: "Rounded accents",
  }),

  createToken({ name: "--text-display-xl", value: "3.000rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-display-lg", value: "2.500rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-display", value: "2.125rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-title-1", value: "1.750rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-title-2", value: "1.375rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-title-3", value: "1.250rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-title-4", value: "1.125rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-headline", value: "1.063rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-body-lg", value: "1.063rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-body", value: "1.000rem", category: "type-scale", section: "type-scale", comment: "1rem anchor" }),
  createToken({ name: "--text-body-sm", value: "0.938rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-label-lg", value: "0.875rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-label", value: "0.813rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-caption", value: "0.750rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-caption-sm", value: "0.688rem", category: "type-scale", section: "type-scale" }),
  createToken({ name: "--text-micro", value: "0.625rem", category: "type-scale", section: "type-scale", comment: "Wearable / badge text" }),

  createToken({ name: "--leading-watch", value: "1.00", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-tight", value: "1.08", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-display", value: "1.12", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-snug", value: "1.20", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-title", value: "1.25", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-heading", value: "1.35", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-reading", value: "1.60", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-compact", value: "1.50", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-ui", value: "1.40", category: "line-height", section: "line-height" }),
  createToken({ name: "--leading-caption", value: "1.35", category: "line-height", section: "line-height" }),

  createToken({ name: "--tracking-display", value: "-0.025em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-tight", value: "-0.018em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-title", value: "-0.010em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-normal", value: "0.000em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-label", value: "0.010em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-caption", value: "0.025em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-overline", value: "0.060em", category: "letter-spacing", section: "letter-spacing" }),
  createToken({ name: "--tracking-watch", value: "0.040em", category: "letter-spacing", section: "letter-spacing" }),

  createToken({ name: "--weight-thin", value: "100", category: "font-weight", section: "font-weight" }),
  createToken({ name: "--weight-extralight", value: "200", category: "font-weight", section: "font-weight" }),
  createToken({ name: "--weight-light", value: "300", category: "font-weight", section: "font-weight" }),
  createToken({ name: "--weight-regular", value: "400", category: "font-weight", section: "font-weight", comment: "Body text" }),
  createToken({ name: "--weight-medium", value: "500", category: "font-weight", section: "font-weight", comment: "Labels, callouts" }),
  createToken({ name: "--weight-semibold", value: "600", category: "font-weight", section: "font-weight", comment: "Headlines, titles" }),
  createToken({ name: "--weight-bold", value: "700", category: "font-weight", section: "font-weight", comment: "Display, emphasis" }),
  createToken({ name: "--weight-extrabold", value: "800", category: "font-weight", section: "font-weight", comment: "Hero display" }),
  createToken({ name: "--weight-black", value: "900", category: "font-weight", section: "font-weight", comment: "Maximum impact" }),

  createToken({ name: "--space-unit", value: "0.25rem", category: "spatial", section: "spatial", subcategory: "space", comment: "4px at 16px root" }),
  createToken({ name: "--space-0", value: "0rem", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-1", value: "calc(var(--space-unit) * 1)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-2", value: "calc(var(--space-unit) * 2)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-3", value: "calc(var(--space-unit) * 3)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-4", value: "calc(var(--space-unit) * 4)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-5", value: "calc(var(--space-unit) * 5)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-6", value: "calc(var(--space-unit) * 6)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-8", value: "calc(var(--space-unit) * 8)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-10", value: "calc(var(--space-unit) * 10)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-12", value: "calc(var(--space-unit) * 12)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-16", value: "calc(var(--space-unit) * 16)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-20", value: "calc(var(--space-unit) * 20)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-24", value: "calc(var(--space-unit) * 24)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-32", value: "calc(var(--space-unit) * 32)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-xs", value: "var(--space-1)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-sm", value: "var(--space-2)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-md", value: "var(--space-4)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-lg", value: "var(--space-6)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-xl", value: "var(--space-8)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-2xl", value: "var(--space-12)", category: "spatial", section: "spatial", subcategory: "space" }),
  createToken({ name: "--space-3xl", value: "var(--space-16)", category: "spatial", section: "spatial", subcategory: "space" }),

  createToken({ name: "--target-min", value: "2.75rem", category: "spatial", section: "spatial", subcategory: "target" }),
  createToken({ name: "--target-md", value: "3.00rem", category: "spatial", section: "spatial", subcategory: "target" }),
  createToken({ name: "--target-lg", value: "3.50rem", category: "spatial", section: "spatial", subcategory: "target" }),
  createToken({ name: "--target-xl", value: "4.00rem", category: "spatial", section: "spatial", subcategory: "target" }),
  createToken({ name: "--target-watch", value: "2.00rem", category: "spatial", section: "spatial", subcategory: "target" }),

  createToken({ name: "--radius-none", value: "0rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-xs", value: "0.125rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-sm", value: "0.25rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-md", value: "0.5rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-lg", value: "0.75rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-xl", value: "1.0rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-2xl", value: "1.5rem", category: "spatial", section: "spatial", subcategory: "radius" }),
  createToken({ name: "--radius-full", value: "9999rem", category: "spatial", section: "spatial", subcategory: "radius" }),

  createToken({ name: "--border-hairline", value: "0.5px", category: "spatial", section: "spatial", subcategory: "border" }),
  createToken({ name: "--border-thin", value: "1px", category: "spatial", section: "spatial", subcategory: "border" }),
  createToken({ name: "--border-md", value: "2px", category: "spatial", section: "spatial", subcategory: "border" }),
  createToken({ name: "--border-thick", value: "4px", category: "spatial", section: "spatial", subcategory: "border" }),

  createToken({ name: "--icon-xs", value: "0.75rem", category: "spatial", section: "spatial", subcategory: "icon" }),
  createToken({ name: "--icon-sm", value: "1.0rem", category: "spatial", section: "spatial", subcategory: "icon" }),
  createToken({ name: "--icon-md", value: "1.25rem", category: "spatial", section: "spatial", subcategory: "icon" }),
  createToken({ name: "--icon-lg", value: "1.5rem", category: "spatial", section: "spatial", subcategory: "icon" }),
  createToken({ name: "--icon-xl", value: "2.0rem", category: "spatial", section: "spatial", subcategory: "icon" }),
  createToken({ name: "--icon-2xl", value: "3.0rem", category: "spatial", section: "spatial", subcategory: "icon" }),
  createToken({ name: "--icon-watch", value: "1.125rem", category: "spatial", section: "spatial", subcategory: "icon" }),

  createToken({ name: "--measure-narrow", value: "30ch", category: "spatial", section: "spatial", subcategory: "measure" }),
  createToken({ name: "--measure-normal", value: "66ch", category: "spatial", section: "spatial", subcategory: "measure" }),
  createToken({ name: "--measure-wide", value: "80ch", category: "spatial", section: "spatial", subcategory: "measure" }),
  createToken({ name: "--measure-full", value: "100%", category: "spatial", section: "spatial", subcategory: "measure" }),

  createToken({ name: "--shadow-0", value: "none", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-1", value: "0 1px 2px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.06)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-2", value: "0 2px 4px rgba(0,0,0,0.08), 0 4px 8px rgba(0,0,0,0.06)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-3", value: "0 4px 8px rgba(0,0,0,0.10), 0 8px 16px rgba(0,0,0,0.08)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-4", value: "0 8px 16px rgba(0,0,0,0.12), 0 16px 32px rgba(0,0,0,0.08)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-5", value: "0 16px 32px rgba(0,0,0,0.14), 0 24px 48px rgba(0,0,0,0.10)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-inset-sm", value: "inset 0 1px 2px rgba(0,0,0,0.10)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-inset-md", value: "inset 0 2px 4px rgba(0,0,0,0.12)", category: "shadow", section: "shadow", variant: "base" }),
  createToken({ name: "--shadow-1", value: "0 1px 2px rgba(0,0,0,0.30), 0 1px 3px rgba(0,0,0,0.20)", category: "shadow", section: "shadow", variant: "dark" }),
  createToken({ name: "--shadow-2", value: "0 2px 4px rgba(0,0,0,0.35), 0 4px 8px rgba(0,0,0,0.25)", category: "shadow", section: "shadow", variant: "dark" }),
  createToken({ name: "--shadow-3", value: "0 4px 8px rgba(0,0,0,0.40), 0 8px 16px rgba(0,0,0,0.30)", category: "shadow", section: "shadow", variant: "dark" }),
  createToken({ name: "--shadow-4", value: "0 8px 16px rgba(0,0,0,0.45), 0 16px 32px rgba(0,0,0,0.35)", category: "shadow", section: "shadow", variant: "dark" }),
  createToken({ name: "--shadow-5", value: "0 16px 32px rgba(0,0,0,0.50), 0 24px 48px rgba(0,0,0,0.40)", category: "shadow", section: "shadow", variant: "dark" }),

  createToken({ name: "--z-below", value: "-1", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-base", value: "0", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-raised", value: "10", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-dropdown", value: "100", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-sticky", value: "200", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-overlay", value: "300", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-drawer", value: "400", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-modal", value: "500", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-popover", value: "600", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-toast", value: "700", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-alert", value: "800", category: "z-index", section: "z-index" }),
  createToken({ name: "--z-top", value: "900", category: "z-index", section: "z-index" }),

  createToken({ name: "--duration-micro", value: "50ms", category: "motion", section: "motion", subcategory: "duration" }),
  createToken({ name: "--duration-fast", value: "100ms", category: "motion", section: "motion", subcategory: "duration" }),
  createToken({ name: "--duration-standard", value: "200ms", category: "motion", section: "motion", subcategory: "duration" }),
  createToken({ name: "--duration-slow", value: "300ms", category: "motion", section: "motion", subcategory: "duration" }),
  createToken({ name: "--duration-enter", value: "250ms", category: "motion", section: "motion", subcategory: "duration" }),
  createToken({ name: "--duration-exit", value: "150ms", category: "motion", section: "motion", subcategory: "duration" }),
  createToken({ name: "--duration-page", value: "400ms", category: "motion", section: "motion", subcategory: "duration" }),

  createToken({ name: "--ease-standard", value: "cubic-bezier(0.2, 0.0, 0.0, 1.0)", category: "motion", section: "motion", subcategory: "easing" }),
  createToken({ name: "--ease-decelerate", value: "cubic-bezier(0.0, 0.0, 0.2, 1.0)", category: "motion", section: "motion", subcategory: "easing" }),
  createToken({ name: "--ease-accelerate", value: "cubic-bezier(0.4, 0.0, 1.0, 1.0)", category: "motion", section: "motion", subcategory: "easing" }),
  createToken({ name: "--ease-spring", value: "cubic-bezier(0.34, 1.56, 0.64, 1.0)", category: "motion", section: "motion", subcategory: "easing" }),
  createToken({ name: "--ease-linear", value: "linear", category: "motion", section: "motion", subcategory: "easing" }),

  createToken({ name: "--transition-fast", value: "var(--duration-fast) var(--ease-standard)", category: "motion", section: "motion", subcategory: "transition" }),
  createToken({ name: "--transition-std", value: "var(--duration-standard)  var(--ease-standard)", category: "motion", section: "motion", subcategory: "transition" }),
  createToken({ name: "--transition-slow", value: "var(--duration-slow)      var(--ease-standard)", category: "motion", section: "motion", subcategory: "transition" }),
  createToken({ name: "--transition-enter", value: "var(--duration-enter)     var(--ease-decelerate)", category: "motion", section: "motion", subcategory: "transition" }),
  createToken({ name: "--transition-exit", value: "var(--duration-exit)      var(--ease-accelerate)", category: "motion", section: "motion", subcategory: "transition" }),
];
